# Generated by Django 4.2.6 on 2023-10-05 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=10)),
                ('Contact', models.CharField(max_length=10)),
                ('Created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=10)),
                ('Desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RoomNumber', models.CharField(max_length=10)),
                ('RoomDesc', models.CharField(max_length=10)),
                ('StatusID', models.IntegerField()),
                ('Created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('EstateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estate')),
            ],
        ),
    ]
